### ISSUE TITLE
[Windows] VSCode not open when alt + click

### ISSUE THREAD

**Issue by Kvodnon** [siddharthkp/babel-plugin-open-source#4]
Hi. I install package with npm, set package name in babel config as packages. Open localhost site, hold **alt** and click **LMB**, opened new browser window with file url location and it close. VSCode don't open file. How i can resolve it?
OS: Windows 10

**Comment by siddharthkp** [comment]
Hi! I have not tried this on windows, so you'll have to try it for me :)

Does this approach work for you in general: https://stackoverflow.com/a/18246357

if you write a file link in the url bar with `vscode`, does it open the file for you?

`vscode:///C:\my-apps\example\index.js`

**Comment by siddharthkp** [comment]
closing this, feel free to reply back and i'll reopen the issue

**Comment by Kvodnon** [comment]
It's working for me: https://stackoverflow.com/questions/58305094/opening-files-through-url-handling-doesnt-open-file-in-files-own-workspace

vscode://file/C:\my-apps\example\index.js opens
but
vscode:///C:\my-apps\example\index.js not

**Comment by siddharthkp** [comment]
That's very helpful! Can detect windows and use a different path :) 

Would you like to create a PR for that?

**Comment by Kvodnon** [comment]
> That's very helpful! Can detect windows and use a different path :)
> 
> Would you like to create a PR for that?

Already :)
