### ISSUE TITLE
Support jetbrains

### ISSUE THREAD

**Issue by katsenkatorz** [siddharthkp/babel-plugin-open-source#6]
Can you add support for jetbrains IDE or more like vim  ? 

For jetbrains you can do like this for url `phpstorm://open?file=/Users/..../foo.js&line=24`

I think, you can choose ide by .env variable and get in file with `process.env.IDE_EXAMPLE_VAR_NAME === 'PhpStorm'`
Default vscode if .env is not configure.

What do you think ?

Thanks in advance

**Comment by siddharthkp** [comment]
Hi!

I think this PR will open up room for more editors: https://github.com/siddharthkp/babel-plugin-open-source/pull/1

+ can you link to a reference which has the url format?
